# Generated by Django 2.2.1 on 2019-05-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_gmm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acousticmodel',
            old_name='user',
            new_name='author',
        ),
    ]
