# Generated by Django 2.2.1 on 2019-05-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_gmm', '0002_auto_20190522_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acousticmodel',
            old_name='author',
            new_name='user',
        ),
    ]
