# Generated by Django 2.2.1 on 2019-05-19 21:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_audio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='audio_data',
            field=models.FileField(null=True, upload_to=accounts.models.return_path),
        ),
    ]
