# Generated by Django 2.2.1 on 2019-05-22 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190519_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='audio_data',
        ),
    ]
