# Generated by Django 2.2.1 on 2019-05-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190516_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audio_data',
            field=models.FileField(null=True, upload_to='profile_access'),
        ),
    ]
